### PR TITLE
Add values to Augmentation functions

### PR DESCRIPTION
**Pull request by shuoli84**
This is a rough workable version to handle duplicate values with "Upsert" approach.

### CODE REVIEW

**Comment by shuoli84** [comment]
#24 ref

**Comment by YeungOnion** [comment]
Hmm, but key removal and reinsertion might require rebalancing twice (I did not prove this, but I believe it is true). 

Perhaps I am simply wanting too specific of a behavior from a general data structure while maintaining all of its advantages.

**Comment by shuoli84** [comment]
Just tweaked the Augmentation trait, and pass in the values reference. The code indead looks much cleaner.
But "get_mut" functions won't update the augmentation. I think it is ok as long as we make it clear in the doc..

**Comment by shuoli84** [comment]
```// insert key into tree, if it already exists, then increase count
fn insert(tree: &mut BPlusTree<NodeStoreVec<i64, usize, Count>>, key: i64) {
    let prev_count = tree.get(&key).cloned().unwrap_or_default();
    tree.insert(key, prev_count + 1);
}

fn delete(tree: &mut BPlusTree<NodeStoreVec<i64, usize, Count>>, key: i64) {
    let prev_count = tree.get(&key).cloned().unwrap_or_default();
    if prev_count == 1 {
        tree.remove(&key);
    } else {
        tree.insert(key, prev_count - 1);
    }
}```

**Comment by YeungOnion** [comment]
Hey thanks for doing this!

I suppose that implementing key only augmentations will be optimized by the compiler. Did you compare any benchmarks to make sure you're not losing out on perf?

**Comment by shuoli84** [comment]
Noop, I did not do any benchmark yet. I believe the compiler should kick in and optimize it, but that's hard to say... It would be great to define a new set of benchmark for augmentation features. 

Before doing that, do you think the implementation suits your use case?

**Comment by YeungOnion** [comment]
It looks to me like the `count_as_value` example is what I need. I tried it in a few different cases, and it seems to work as expected.

So is your plan to document that values can be used, but that implementors of `Augmentation` should know that there will be logical errors if values are mutated in-place instead of with the insertion API?

**Comment by shuoli84** [comment]
Yup. I think the use case is common and the likelihood of both "get_mut and update" + "Augmentation based on Value" is low.

**Comment by YeungOnion** [comment]
I think so as well, and at least it would only be a logic error, similar to mutating key in-place in a `collections::BTree*`

**Pull request merged**
