### PR TITLE
Explicitly specify various missing trait impls 

### PR DESCRIPTION
**Pull request by michaelsutton**
1. Implement Clone, Default for custom Argument types
2. Expose map iterator as DoubleEnded, ExactSize, Fused

### CODE REVIEW

**Review by shuoli84 — APPROVED** [review]
LGTM

**Comment by shuoli84** [comment]
thanks

**Comment by michaelsutton** [comment]
> thanks

Would you like work to be done for fixing new clippy warnings?

**Comment by shuoli84** [comment]
@michaelsutton that will be great. It's been a while since my last change, I also need some time to pick it up. Would you like to open a PR? I'll do what I can do :)

**Pull request merged**
